apiVersion: apps/v1
kind: Deployment
metadata:
  name: bmkflask-app
  labels:
    app: bmkflask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bmkflask
  template:
    metadata:
      labels:
        app: bmkflask
    spec:
      containers:
      - name: bmkflask
        image: yenaing/python_flask
        ports:
        - containerPort: 5000
        securityContext:
          privileged: true
        volumeMounts:
        - name: hostvol
          mountPath: /opt
      volumes:
        - name: hostvol
          persistentVolumeClaim:
            # PVC name you created
            claimName: bmkflask-pvc
