apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: yenaing/python_flask
        ports:
        - containerPort: 5000
        securityContext:
          privileged: true
        volumeMounts:
        - name: hostvol
          mountPath: /opt
      volumes:
        - name: hostvol
          persistentVolumeClaim:
            # PVC name you created
            claimName: flask-pvc
