apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # any PVC name
  name: flask-pvc
spec:
  storageClassName: flask001
  accessModes:
  # ReadWriteMany(RW from multi nodes), ReadWriteOnce(RW from a node), ReadOnlyMany(R from multi nodes)
    - ReadWriteMany
  resources:
    requests:
       # storage size to use
      storage: 5Gi
